[package]
name = "redlang"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.11.0"
encoding = "0.2.33"
getrandom = "0.2.8"
base64 = "0.21.2"
serde_json = "1.0.104"
serde_derive = "1.0.166"
serde = {version = "1.0.166",features = ["derive"]}
uuid = {version = "1.4.1",features = ["v4","fast-rng"]}
lazy_static = "1.4.0"
chrono = "0.4.26"
md-5 = "0.10.5"
rcnb-rs = "0.1.0"
rust-embed="6.8.1"
image = "0.24.6"
imageproc = "0.23.0"
gif = "0.12.0"
cron = "0.12.0"
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
url = "2.4.0"
futures-util = "0.3.28"
hyper-tungstenite = "0.13.0"
tokio-tungstenite = { version ="0.21.0",default-features = false,features = ["rustls-tls-webpki-roots"] }
scopeguard = "1.2.0"
log = "0.4.19"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter","time","local-time"]}
opener = "0.6.1"
rusqlite = {version = "0.29.0",features = ["bundled"]}
sevenz-rust = "0.4.3"
jsonpath-rust = "0.3.1"
rusttype = "0.9.3"
# markdown = "1.0.0-alpha.7"
reqwest = {version = "0.11.18",default-features = false,features = ["rustls-tls","multipart"]}
time = { version = "0.3.25", features = ["formatting", "macros"] }
# headless_chrome = {version="1.0.5",default-features = false}
webp = "0.2.5"
sysinfo = "0.29.10"
resvg = { version = "0.36.0", default-features = false, features = [ "text", "raster-images"  ] }
fontdb = { version = "0.15.0", default-features = false, features = [ "fs" ] }
flate2 = { version = "1.0.26",default-features = false}
zhconv = "0.3.0"
async-trait = "0.1.74"
tl = "0.7.7"
html-escape = "0.2.13"
libloading = "0.8.1"
tokio-util = { version = "0.7.10", default-features = false, features = [ "io" ] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
bytes = "1.5.0"
zip = "0.6.6"


[target.'cfg(windows)'.dependencies]
winreg = "0.50.0"
screenshots = "0.7.1"


[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols

