name: Build Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  test:
    name: build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: rust_install
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: install_cross
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
    - name: build
      run: |
        cross build --target aarch64-linux-android --release
        strip target/aarch64-linux-android/release/redlang
        cross build --target i686-pc-windows-gnu --release
        strip target/i686-pc-windows-gnu/release/redlang.exe
        cross build --target aarch64-unknown-linux-musl --release
        strip target/aarch64-unknown-linux-musl/release/redlang
        cross build --target i686-unknown-linux-musl --release
        strip target/i686-unknown-linux-musl/release/redlang
        
    - name: before_upload
      run: |
        mkdir Release
        cp target/aarch64-linux-android/release/redlang Release/redlang_android_aarch64
        cp target/i686-pc-windows-gnu/release/redlang.exe Release/redlang_windows_i686.exe
        cp target/aarch64-unknown-linux-musl/release/redlang Release/redlang_linux_aarch64
        cp target/i686-unknown-linux-musl/release/redlang Release/redlang_linux_i686

    - name: upload file1
      uses: actions/upload-artifact@v3
      with:
        name: redlang_windows_i686.exe
        path: 
            Release/redlang_windows_i686.exe

    - name: upload file2
      uses: actions/upload-artifact@v3
      with:
        name: redlang_linux_aarch64
        path: 
            Release/redlang_linux_aarch64

    - name: upload file3
      uses: actions/upload-artifact@v3
      with:
        name: redlang_linux_i686
        path: 
          Release/redlang_linux_i686

    - name: upload file4
      uses: actions/upload-artifact@v3
      with:
        name: redlang_android_aarch64
        path: 
          Release/redlang_android_aarch64
